### PR TITLE
Ah support

### PR DESCRIPTION
**Pull request by jonwho**
extendedPrice on IEX is actually both pre & post market values

can only tell which is which based on the extendedTime value

### CODE REVIEW

**Comment by jonwho** [comment]
this has changeset from other pr so should review+merge that first to see cleaner changeset for this PR

**Comment by jonwho** [comment]
image

**Comment by BryanSLam** [comment]
hmm this one might need to wait till I have time to actually review.

my initial thoughts are that there are way too many values now, why can't you just have it use the pre/post price when the current time is pre-market or post-market?

**Comment by jonwho** [comment]
if we don't care about comparing open trading vs extended trading times im ok to switch to timing logic and re-use current values

**Comment by BryanSLam** [comment]
yeah I don't think theres a lot of need to compare, its not meant to be used for stock analysis, just a quick quote, so it should be verbose

if there's a need we can make a more in-depth command that has more info

**Comment by BryanSLam** [comment]
can you ss what it looks like now

**Comment by jonwho** [comment]
image

**Comment by BryanSLam** [comment]
Hmm I don't think we need time in the quote

Can you make it so current price uses the after/pre price during those hours and same with change and Delta?

**Comment by jonwho** [comment]
new ss's  in the channel

**Comment by jonwho** [comment]
think adding bh/ah per field gets noisy and looks weird. feel PR good as-is

**Review by BryanSLam — APPROVED** [review]

**Pull request merged**
