### PR TITLE
Use my sick lib

### PR DESCRIPTION
**Pull request by jonwho**
Updated the quote to use new client

Also added new command `!er <stock>` to see latest earnings report

The datasource pkg belongs to you so I'll let you delete the `stock.go` file

### CODE REVIEW

**Comment by jonwho** [comment]
image

**Comment by BryanSLam** [comment]
Whats announce time?

**Comment by jonwho** [comment]
BTO is before the open
AMC is after market close

there's also DMC during market... something

**Comment by BryanSLam** [comment]
can you make it explicit then? I don't think the acronym is obvious to most people

also I'm not a super big fan of removing the `stock` object in lieu of your library.  partly because it's odd that one object is represented (`coin`) while the other is just output that gets formatted from an API.

I think having a wrapper for the API is good, but the client should be using your wrapper the same way it'd use the actual IEX API endpoint, but with less pain because its a go library, so moving away from representing the stock info in an object is kinda counter intuitive

**Comment by jonwho** [comment]
image

**Review by BryanSLam — APPROVED** [review]

**Pull request merged**
